import { Globe, Sprout, Recycle, Shield, Star, Gem, Crown } from "lucide-react";

export const rewardLevels = [
  {
    id: 1,
    name: "Eco Beginner",
    minRecycles: 0,
    maxRecycles: 4,
    color: "bg-gray-50 text-gray-900 border-gray-200",
    icon: Globe,
    benefits: ["Welcome bonus: 50 points", "1 points per recycling order"],
    badge: Globe,
  },
  {
    id: 2,
    name: "Eco Starter",
    minRecycles: 5,
    maxRecycles: 14,
    color: "bg-gray-100 text-gray-800 border-gray-300",
    icon: Sprout,
    benefits: ["Reaching bonus: 150 points", "5 points per recycling order"],
    badge: Sprout,
  },
  {
    id: 3,
    name: "Green Helper",
    minRecycles: 15,
    maxRecycles: 29,
    color: "bg-green-100 text-green-800 border-green-300",
    icon: Recycle,
    benefits: ["Reaching bonus: 300 points", "10 points per recycling order"],
    badge: Recycle,
  },
  {
    id: 4,
    name: "Silver Recycler",
    minRecycles: 30,
    maxRecycles: 49,
    color: "bg-gray-200 text-gray-700 border-gray-400",
    icon: Shield,
    benefits: ["Reaching bonus: 500 points", "15 points per recycling order"],
    badge: Shield,
  },
  {
    id: 5,
    name: "Gold Guardian",
    minRecycles: 50,
    maxRecycles: 74,
    color: "bg-yellow-100 text-yellow-800 border-yellow-300",
    icon: Star,
    benefits: ["Reaching bonus: 700 points", "20 points per recycling order"],
    badge: Star,
  },
  {
    id: 6,
    name: "Platinum Pioneer",
    minRecycles: 75,
    maxRecycles: 99,
    color: "bg-blue-100 text-blue-800 border-blue-300",
    icon: Gem,
    benefits: ["Reaching bonus: 850 points", "25 points per recycling order"],
    badge: Gem,
  },
  {
    id: 7,
    name: "Diamond Elite",
    minRecycles: 100,
    maxRecycles: 999999,
    color: "bg-purple-100 text-purple-800 border-purple-300",
    icon: Crown,
    benefits: ["Reaching bonus: 1000 points", "30 points per recycling order"],
    badge: Crown,
  },
];
