import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserAuthProvider } from "@/context/AuthFormContext";
import { CartProvider } from "@/context/CartContext";
import { ToastContainer } from "react-toastify";
import LayoutWrapper from "@/components/shared/layoutwrapper";

import React from "react";
import ReactQueryProvider from "@/components/providers/reactQueryProvider";
import { Toaster } from "react-hot-toast";
import { NotificationProvider } from "@/context/notificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>)


{

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserAuthProvider>
    <ReactQueryProvider>
          <CartProvider>
            <Toaster/>
            <NotificationProvider>

            <ToastContainer />
            <LayoutWrapper>{children}</LayoutWrapper>
            </NotificationProvider>

          </CartProvider>
          </ReactQueryProvider>
        </UserAuthProvider>

      </body>
    </html>
  );
}
